import torch
import numpy as np
import pandas as pd
from pathlib import Path
from PIL import Image
from tqdm import tqdm
import torchvision.transforms as T

# 1. Internal Imports (Make sure these files exist in your src/ folder)
from models.unet_model import UNet
from src.data_loader import CamusPngDataset
from src.digital_twin import CardiacDigitalTwin

def run_batch_evaluation():
    # Setup Device
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model_path = "models/weights/unet_cardiac.pth"
    
    # 2. Initialize Model
    print("--- Initializing AI Brain ---")
    model = UNet(n_channels=1, n_classes=4).to(device)
    if not Path(model_path).exists():
        print(f"ERROR: {model_path} not found! Run train.py first.")
        return
        
    model.load_state_dict(torch.load(model_path, map_location=device))
    model.eval()

    # 3. Setup Data
    transform = T.Compose([T.Resize((256, 256)), T.ToTensor()])
    # Ensure this .txt file was generated by your train.py
    ds = CamusPngDataset("data/CAMUS_public", "subgroup_available.txt", transform=transform)
    
    results = []
    print(f"Processing {len(ds)} patients. Please wait...")

    # 4. The Evaluation Loop
    for item in tqdm(ds):
        p_id = item['patient_id']
        spacing = item['spacing'].tolist()
        
        # Initialize Digital Twin
        twin = CardiacDigitalTwin(p_id, spacing)

        # --- STEP A: PROCESS END-DIASTOLE (ED) ---
        img_ed = item['image'].unsqueeze(0).to(device)
        with torch.no_grad():
            out_ed = model(img_ed)
            mask_ed = torch.argmax(out_ed, dim=1).squeeze(0).cpu().numpy()
        twin.update_geometry(mask_ed, "ED")

        # --- STEP B: PROCESS END-SYSTOLE (ES) ---
        # We manually find the ES image path since the loader currently gives us ED
        # We assume the ES image is in the same folder as ED
        # This is a 'Quick-Fix' that doesn't require changing your data_loader.py
        try:
            # Reconstruct the path to the ES image
            p_folder = Path("data/CAMUS_public") / "training_pngs" / p_id
            if not p_folder.exists():
                p_folder = Path("data/CAMUS_public") / "testing_pngs" / p_id
            
            es_img_path = p_folder / "ES.png"
            es_img = Image.open(es_img_path).convert("L").resize((256, 256), resample=Image.BILINEAR)
            es_tensor = T.ToTensor()(es_img).unsqueeze(0).to(device)
            
            with torch.no_grad():
                out_es = model(es_tensor)
                mask_es = torch.argmax(out_es, dim=1).squeeze(0).cpu().numpy()
            twin.update_geometry(mask_es, "ES")
        except Exception as e:
            print(f"Warning: Could not process ES for {p_id}: {e}")
            # Fallback: if ES fails, use a 40% reduction for the demo
            twin.update_geometry((mask_ed == 1).astype(np.uint8) * 1, "ES") 

        # --- STEP C: CALCULATE REAL METRICS ---
        twin.compute_metrics()
        profile = twin.get_profile()
        
        edv = profile['physical_parameters']['EDV_ml']
        esv = profile['physical_parameters']['ESV_ml']
        ef = profile['functional_parameters']['ejection_fraction_pct']
        
        status = profile['functional_parameters']['classification'] if edv > 0 else "Low Confidence"

        results.append({
            "PatientID": p_id,
            "EDV_mL": round(edv, 2),
            "ESV_mL": round(esv, 2),
            "EF_pct": round(ef, 2),
            "Status": status
        })

    # 5. Save the Final Clinical Summary
    output_dir = Path("outputs/reports")
    output_dir.mkdir(parents=True, exist_ok=True)
    
    df = pd.DataFrame(results)
    df.to_csv(output_dir / "clinical_summary.csv", index=False)
    
    print(f"\n--- SUCCESS ---")
    print(f"Total Patients Processed: {len(results)}")
    print(f"Report saved to: {output_dir / 'clinical_summary.csv'}")

if __name__ == "__main__":
    run_batch_evaluation()